<h2 style="font-size:30px;font-family:Calibri">
    Logistic Regression
</h2>

In [24]:
from sklearn.linear_model import LogisticRegression, LogisticRegressionCV
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
import numpy as np

<h2 style="font-size:30px;font-family:Calibri">
    Training a Binary Classifier
</h2>

In [25]:
iris = datasets.load_iris()
features = iris.data[:100, :]
target = iris.target[:100]

scaler = StandardScaler()
features_standardized = scaler.fit_transform(features)

In [26]:
logistic_regr = LogisticRegression(random_state = 0)
model = logistic_regr.fit(features_standardized, target)

In [27]:
new_obs = [[.5, .5, .5, .5]]
model.predict(new_obs)

array([1])

In [28]:
model.predict_proba(new_obs)

array([[0.17738424, 0.82261576]])

<h2 style="font-size:30px;font-family:Calibri">
    Training a Multiclass Classifier
</h2>

In [29]:
iris = datasets.load_iris()
features = iris.data
target = iris.target

In [30]:
scaler = StandardScaler()
features_standardized = scaler.fit_transform(features)

In [31]:
logistic_regr = LogisticRegression(random_state = 0, multi_class = "ovr")
model = logistic_regr.fit(features_standardized, target)

<h2 style="font-size:30px;font-family:Calibri">
     Reducing Variance Through
 Regularization
</h2>

In [32]:
logistic_regr = LogisticRegressionCV(penalty = "l2", Cs = 10, n_jobs = -1, random_state = 0)
model = logistic_regr.fit(features_standardized, target)

In [33]:
model.predict(new_obs)

array([1])

In [34]:
model.predict_proba(new_obs).round(3)

array([[0.001, 0.97 , 0.029]])

<h2 style="font-size:30px;font-family:Calibri">
    Training a Classifier on Very Large Data
</h2>

In [35]:
logistic_regr = LogisticRegression(random_state = 0, solver = "sag")
model = logistic_regr.fit(features_standardized, target)

<h2 style="font-size:30px;font-family:Calibri">
    Handling Imbalanced Classes
</h2>

In [36]:
# Make class highly imbalanced by removing first 40 observations
features = features[40:,:]
target = target[40:]

target = np.where((target == 0), 0, 1)

In [37]:
scaler = StandardScaler()
features_standardized = scaler.fit_transform(features)

In [38]:
logistic_regr = LogisticRegression(class_weight = "balanced")
model = logistic_regr.fit(features_standardized, target)