<h1 style="font-size:30px;font-family:Calibri">
    Naive Bayes
</h1>
The Naive Bayes algorithm is a classification algorithm that uses Bayes' theorem to make predictions. 
The algorithm is called "naive" because it doesn't account for dependencies between features.

In [26]:
import numpy as np
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB, MultinomialNB, BernoulliNB
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.calibration import CalibratedClassifierCV

import warnings
warnings.filterwarnings("ignore")

<h1 style="font-size:30px;font-family:Calibri">
    Training a Classifier for Continuous
 Features
</h1>

In [4]:
iris = datasets.load_iris()
features = iris.data
target = iris.target

classifier = GaussianNB()
model = classifier.fit(features, target)

In [5]:
new_obs = [[4, 4, 4, 0.4]]
model.predict(new_obs)

array([1])

In [6]:
clf = GaussianNB(priors = [0.25, 0.25, 0.5])
model = classifier.fit(features, target)

<h1 style="font-size:30px;font-family:Calibri">
    Training a Classifier for Discrete and
 Count Features
</h1>

In [13]:
text_data = np.array([
    'I love Brazil. Brazil!',
    'Brazil is Best',
    'Germany beats both'
])

count = CountVectorizer()
bag_of_words = count.fit_transform(text_data)

In [15]:
features = bag_of_words.toarray()
target = np.array([0, 0, 1])
classifier = MultinomialNB(class_prior = [0.25, 0.5])
model = classifier.fit(features, target)

In [16]:
new_obs = [[0, 0, 0, 1, 0, 1, 0]]
model.predict(new_obs)

array([0])

<h1 style="font-size:30px;font-family:Calibri">
    Training a Naive Bayes Classifier for
Binary Features
</h1>

In [21]:
features = np.random.randint(2, size = (100, 3))
target = np.random.randint(2, size = (100, 1)).ravel()

In [24]:
classifier = BernoulliNB(class_prior = [0.25, 0.5])
model = classifier.fit(features, target)

In [25]:
model_uniform_prior = BernoulliNB(class_prior = None, fit_prior = True)

<h1 style="font-size:30px;font-family:Calibri">
    Calibrating Predicted Probabilities
</h1>

In [27]:
iris = datasets.load_iris()
features = iris.data
target = iris.target

In [30]:
classifier = GaussianNB()
classifier_sigmoid = CalibratedClassifierCV(classifier, cv = 2, method = "sigmoid")
classifier_sigmoid.fit(features, target)
new_obs = [[2.6, 2.6, 2.6, 0.4]]
classifier_sigmoid.predict_proba(new_obs)

array([[0.31859969, 0.63663466, 0.04476565]])

In [31]:
classifier.fit(features, target).predict_proba(new_obs)

array([[2.31548432e-04, 9.99768128e-01, 3.23532277e-07]])

### Done with Day 13 :)